// CMS Mock Data - Ready for Firebase/Firestore migration
import type { Category, Listing, User, TokenPackage, ListingPricing, SiteContent } from "@/types/cms";

export const defaultCategories: Category[] = [
  { id: "property", name: "Property", icon: "Home", color: "bg-emerald-500/10 text-emerald-600", isActive: true, order: 1, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
  { id: "services", name: "Services", icon: "Briefcase", color: "bg-sky-500/10 text-sky-600", isActive: true, order: 2, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
  { id: "vehicles", name: "Vehicles", icon: "Car", color: "bg-blue-500/10 text-blue-600", isActive: true, order: 3, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
  { id: "camping", name: "Camping", icon: "Tent", color: "bg-green-500/10 text-green-600", isActive: true, order: 4, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
  { id: "photography", name: "Photography", icon: "Camera", color: "bg-purple-500/10 text-purple-600", isActive: true, order: 5, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
  { id: "tools", name: "Tools", icon: "Wrench", color: "bg-orange-500/10 text-orange-600", isActive: true, order: 6, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
  { id: "music", name: "Music & Audio", icon: "Music", color: "bg-pink-500/10 text-pink-600", isActive: true, order: 7, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
  { id: "sports", name: "Sports", icon: "Bike", color: "bg-cyan-500/10 text-cyan-600", isActive: true, order: 8, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
  { id: "electronics", name: "Electronics", icon: "Laptop", color: "bg-indigo-500/10 text-indigo-600", isActive: true, order: 9, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
  { id: "furniture", name: "Furniture", icon: "Sofa", color: "bg-amber-500/10 text-amber-600", isActive: true, order: 10, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
  { id: "fashion", name: "Fashion", icon: "Shirt", color: "bg-rose-500/10 text-rose-600", isActive: true, order: 11, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
  { id: "gaming", name: "Gaming", icon: "Gamepad", color: "bg-violet-500/10 text-violet-600", isActive: true, order: 12, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
  { id: "fitness", name: "Fitness", icon: "Dumbbell", color: "bg-red-500/10 text-red-600", isActive: true, order: 13, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
  { id: "kitchen", name: "Kitchen", icon: "ChefHat", color: "bg-teal-500/10 text-teal-600", isActive: true, order: 14, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
];

export const defaultListings: Listing[] = [
  {
    id: "1",
    title: "Professional DJ Equipment Set",
    type: "item",
    category: "Music & Audio",
    price: 850,
    priceUnit: "day",
    location: "Johannesburg, Sandton",
    rating: 4.9,
    reviews: 28,
    image: "https://images.unsplash.com/photo-1571266028243-e4733b0f0bb0?w=600&h=400&fit=crop",
    owner: { name: "Marcus T.", avatar: "https://i.pravatar.cc/100?img=11" },
    isActive: true,
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    title: "4x4 Camping Trailer with Tent",
    type: "item",
    category: "Camping",
    price: 650,
    priceUnit: "day",
    location: "Cape Town, Century City",
    rating: 4.8,
    reviews: 45,
    image: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=600&h=400&fit=crop",
    owner: { name: "Sarah M.", avatar: "https://i.pravatar.cc/100?img=5" },
    isActive: true,
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "3",
    title: "Canon EOS R5 Camera Kit",
    type: "item",
    category: "Photography",
    price: 1200,
    priceUnit: "day",
    location: "Durban, Umhlanga",
    rating: 5.0,
    reviews: 19,
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600&h=400&fit=crop",
    owner: { name: "James K.", avatar: "https://i.pravatar.cc/100?img=12" },
    isActive: true,
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "4",
    title: "Professional Pressure Washer",
    type: "item",
    category: "Tools",
    price: 350,
    priceUnit: "day",
    location: "Pretoria, Menlyn",
    rating: 4.7,
    reviews: 32,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=400&fit=crop",
    owner: { name: "Peter V.", avatar: "https://i.pravatar.cc/100?img=8" },
    isActive: true,
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "5",
    title: "Event Photography Services",
    type: "service",
    category: "Photography",
    price: 2500,
    priceUnit: "event",
    location: "Johannesburg, Rosebank",
    rating: 4.9,
    reviews: 67,
    image: "https://images.unsplash.com/photo-1537633552985-df8429e8048b?w=600&h=400&fit=crop",
    owner: { name: "Lisa N.", avatar: "https://i.pravatar.cc/100?img=9" },
    isActive: true,
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "6",
    title: "Mobile DJ & MC Services",
    type: "service",
    category: "Music & Audio",
    price: 3500,
    priceUnit: "event",
    location: "Cape Town, Claremont",
    rating: 4.8,
    reviews: 89,
    image: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=600&h=400&fit=crop",
    owner: { name: "David O.", avatar: "https://i.pravatar.cc/100?img=15" },
    isActive: true,
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "7",
    title: "Mountain Bike - Trek Fuel EX",
    type: "item",
    category: "Sports",
    price: 400,
    priceUnit: "day",
    location: "Stellenbosch",
    rating: 4.6,
    reviews: 23,
    image: "https://images.unsplash.com/photo-1544191696-102dbdaeeaa0?w=600&h=400&fit=crop",
    owner: { name: "Andre P.", avatar: "https://i.pravatar.cc/100?img=13" },
    isActive: true,
    isFeatured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "8",
    title: "Projector & Screen Set",
    type: "item",
    category: "Electronics",
    price: 500,
    priceUnit: "day",
    location: "Johannesburg, Fourways",
    rating: 4.9,
    reviews: 41,
    image: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=600&h=400&fit=crop",
    owner: { name: "Thandi M.", avatar: "https://i.pravatar.cc/100?img=16" },
    isActive: true,
    isFeatured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "9",
    title: "Personal Training Sessions",
    type: "service",
    category: "Fitness",
    price: 450,
    priceUnit: "session",
    location: "Cape Town, Sea Point",
    rating: 5.0,
    reviews: 56,
    image: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600&h=400&fit=crop",
    owner: { name: "Mike R.", avatar: "https://i.pravatar.cc/100?img=3" },
    isActive: true,
    isFeatured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const defaultTokenPackages: TokenPackage[] = [
  { id: "1", name: "Starter", tokens: 10, price: 50, currency: "ZAR", isPopular: false, isActive: true, order: 1, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
  { id: "2", name: "Popular", tokens: 25, price: 100, currency: "ZAR", isPopular: true, isActive: true, order: 2, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
  { id: "3", name: "Pro", tokens: 60, price: 200, currency: "ZAR", isPopular: false, isActive: true, order: 3, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
  { id: "4", name: "Business", tokens: 150, price: 400, currency: "ZAR", isPopular: false, isActive: true, order: 4, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
];

export const defaultListingPricing: ListingPricing[] = [
  { id: "1", categoryId: "property", tokensRequired: 5, durationDays: 30, renewalTokens: 3, isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
  { id: "2", categoryId: "services", tokensRequired: 3, durationDays: 30, renewalTokens: 2, isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
  { id: "3", categoryId: "vehicles", tokensRequired: 4, durationDays: 30, renewalTokens: 2, isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
  { id: "default", categoryId: "default", tokensRequired: 2, durationDays: 30, renewalTokens: 1, isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
];

export const defaultUsers: User[] = [
  { id: "admin", email: "admin@rent4hire.com", name: "Admin User", role: "admin", tokenBalance: 0, isActive: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() },
];

export const defaultSiteContent: SiteContent[] = [
  { id: "1", key: "hero_title", value: "Rent What You Need, When You Need It", type: "text", section: "hero", updatedAt: new Date().toISOString() },
  { id: "2", key: "hero_subtitle", value: "Discover thousands of items and services available for rent. From cameras to camping gear, find exactly what you need.", type: "text", section: "hero", updatedAt: new Date().toISOString() },
  { id: "3", key: "site_name", value: "Rent4Hire", type: "text", section: "global", updatedAt: new Date().toISOString() },
];
